# Cross-compile toolchain: Linux clang + ld64.lld -> macOS (arm64 / x86_64) .component bundle.
# Needs a MacOSX.sdk (default ~/.macos-sdk/MacOSX.sdk; extract it from an Xcode .xip with
# scripts/extract-macos-sdk.py). On a real Mac, don't use this file — plain `cmake` works.
# Architecture: -DMAC_ARCH=arm64 (default) or x86_64; build both + llvm-lipo for universal.
set(CMAKE_SYSTEM_NAME Darwin)
if(NOT MAC_ARCH)
  set(MAC_ARCH arm64)
endif()
set(CMAKE_SYSTEM_PROCESSOR ${MAC_ARCH})
if(DEFINED ENV{MACOS_SDK})
  set(CMAKE_OSX_SYSROOT "$ENV{MACOS_SDK}")
else()
  set(CMAKE_OSX_SYSROOT "$ENV{HOME}/.macos-sdk/MacOSX.sdk")
endif()
set(CMAKE_OSX_DEPLOYMENT_TARGET 11.0)
set(CMAKE_OSX_ARCHITECTURES ${MAC_ARCH})

find_program(_clang clang REQUIRED NO_CMAKE_FIND_ROOT_PATH)
find_program(_clangxx clang++ REQUIRED NO_CMAKE_FIND_ROOT_PATH)
set(CMAKE_C_COMPILER ${_clang})
set(CMAKE_CXX_COMPILER ${_clangxx})
set(CMAKE_OBJC_COMPILER ${_clang})
set(CMAKE_OBJCXX_COMPILER ${_clangxx})
set(_triple "${MAC_ARCH}-apple-macos11")
foreach(lang C CXX OBJC OBJCXX)
  set(CMAKE_${lang}_COMPILER_TARGET ${_triple})
endforeach()
set(CMAKE_LINKER_TYPE LLD)
set(_ld "-fuse-ld=lld -Wl,-platform_version,macos,11.0,14.5")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${_ld}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "${_ld}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${_ld}")
set(CMAKE_AR llvm-ar)
set(CMAKE_RANLIB llvm-ranlib)
set(CMAKE_INSTALL_NAME_TOOL llvm-install-name-tool)
set(CMAKE_FIND_ROOT_PATH "${CMAKE_OSX_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
